#!/bin/bash
set -e

# Test each project on its own (plus _common):

for dir in jenkins-jobs/*/;
do 
    jenkins-jobs test --recursive "jenkins-jobs/_common:$dir"
done

# Test all the definitions together:

jenkins-jobs test --recursive jenkins-jobs
